### ISSUE TITLE
Bee specific in commit messages

### ISSUE THREAD

**Issue by tjbenator** [NewEdenMC/WebsiteLink#1]
Mind your git manners:
https://blog.8thlight.com/kevin-liddle/2012/09/27/mind-your-git-manners.html

**Comment by tjbenator** [comment]
![WHY YOU NO REPLY](https://cdn.meme.am/instances/500x/53102249.jpg)

**Comment by AaronMcHale** [comment]
Cause

**Comment by tjbenator** [comment]
![But why?](https://cdn.meme.am/instances/43163745.jpg)

**Comment by tjbenator** [comment]
![](http://www.mememaker.net/static/images/memes/4493533.jpg)

**Comment by AaronMcHale** [comment]
idk
